language: python
# Alpaca API only supports 3.5+
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r config/requirements.txt
  - TEST_CMD="black --check --verbose ."
# command to run tests
script:
  - $TEST_CMD 
